Repository CrowdStrike/falcon-openshift-console-plugin, pull requests merged in 2024-09, with the labels that each got.

#1 Virt tab redesign
  README.md
  img/screenshot-vm.png
  src/components/virt/DetectionsTable.tsx
  src/components/virt/EndpointDetails.tsx
  src/components/virt/HealthItem.tsx
  src/components/virt/ProcessTree.tsx
  src/components/virt/SecurityOverview.tsx
  src/components/virt/VirtualMachineTab.tsx
  src/components/virt/VulnsTable.tsx
  src/components/virt/style.css
Labels: enhancement

#2 ci: update and add new workflows
  .github/workflows/ci.yml
  .github/workflows/container_build.yml
  .github/workflows/linting.yml
Labels: ci

#4 Lint fixes
  .eslintrc.yml
  .github/workflows/ci.yml
  .github/workflows/container_build.yml
  .github/workflows/linting.yml
  .stylelintrc.yaml
  src/components/missing-pf-styles.css
  src/components/pod/PodTab.tsx
  src/components/virt/DetectionsTable.tsx
  src/components/virt/NoAgent.tsx
  src/components/virt/VulnsTable.tsx
  src/components/virt/style.css
Labels: lint

#3 docs: update readme
  README.md
  img/crowdstrike.png
Labels: documentation

#5 Pod tab
  README.md
  img/screenshot-pod.png
  package.json
  src/components/pod/ImageAssessment.tsx
  src/components/pod/ImageDetectionsCard.tsx
  src/components/pod/ImageVulnsCard.tsx
  src/components/pod/PodTab.tsx
  src/components/shared/FindingsList.tsx
  src/components/shared/finding-list.css
  yarn.lock
Labels: enhancement

#6 bump v0.1.0
  package.json
Labels: release

#7 feat: add Runtime Detections for Pod view
  src/components/pod/PodTab.tsx
  src/components/pod/RuntimeDetectionsCard.tsx
  src/components/shared/FindingsList.tsx
Labels: enhancement
